In [29]:
def append_to_file(input_file, output_file, additional_content):
    # 打开指定的文件并读取内容
    with open(input_file, 'r') as f:
        original_content = f.read()

    # 将额外的内容添加到原始内容的末尾
    new_content = original_content + '\n' + additional_content

    # 将新内容写入到新文件中
    with open(output_file, 'w') as f:
        f.write(new_content)

# 定义要追加到文件末尾的内容
additional_content = "This is some additional content."

# 调用函数并指定输入文件、输出文件和额外内容
append_to_file('template.ts', 'train.ts', additional_content)

In [27]:
# 定义一个二维数组
two_dimensional_array = [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]

# 使用嵌套的列表推导式遍历二维数组并生成字符串
result_string = ":".join([",".join(map(str, row)) for row in two_dimensional_array])

# 打印生成的字符串
print(result_string)


1,2,3:4,5,6:7,8,9


In [26]:
my_set = {4, 2, 7, 1, 3, 3}

print(my_set.pop())
print(my_set.pop())
my_set.



1
2


In [15]:
import numpy as np

# 定义数组的行数和列数
rows = 50
cols = 6

# 使用 NumPy 生成一个随机整数数组
array = np.random.randint(0, 100, size=(rows, cols))

# 打印生成的数组
print(array)

print(np.transpose(array[0:38]))


[[87 26 21 15 94 12]
 [29 23 88 54 76 23]
 [34 47 76 85 81 22]
 [74  8 70 82 96 46]
 [98 59 29 71 57 87]
 [66 87 69 89 83 62]
 [74 42 57 69 65 94]
 [41 67 87 14 76 54]
 [80 22  6 92 53 13]
 [71 58 98 57 75 12]
 [ 1 64 99 69 79 34]
 [58 80 50 59 30 31]
 [58 77 49 80 77 35]
 [41 59 35 93  0 71]
 [20 48 61 45 27 45]
 [97 60  2 15 13 21]
 [47 23 45 42 12 78]
 [ 7 40 51 50 61 17]
 [ 6 86 65 62 62  3]
 [68 95 69 81 21 91]
 [ 1 72 18 24 20 98]
 [ 4 65 72 97 64 89]
 [42 54 11 99  7 95]
 [17 59 64 30 32 64]
 [31 92 18 97 23  0]
 [45 38 37  6 69 75]
 [65 65 32 90 34 46]
 [13 54 70  3 89  1]
 [92 28  3 97 77 36]
 [73 39 67 64 85  3]
 [51 31 43 91 54 71]
 [68 30 58 56 86 10]
 [ 2 59 38 14 36 13]
 [89 40 16 13 12 89]
 [20 58 19 27 10 73]
 [ 5 44 20  7  6 52]
 [26 78 40 84 24 74]
 [81 40 38 38  1 56]
 [50 84 54 17 54 89]
 [18 98  1 40 75 34]
 [63  1 82 45 97 29]
 [55  9 32 15 57 95]
 [88 98 42 69 62 40]
 [19 38 36 63 16 23]
 [28 60  3 76 43 11]
 [31 14  2  0 74 61]
 [ 1 68  3 82 58  3]
 [94  7 61 91

In [11]:
# 定义一个矩阵
matrix = np.array([[1, 2, 3, 4, 5, 6],
                   [4, 5, 6, 4, 5, 6],
                   [7, 8, 9, 4, 5, 6]])

print(matrix[1:2])

[[4 5 6 4 5 6]]


In [9]:
# 定义一个数组
array = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
         21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

# 每十个一组判断数组中的元素是否相等
for i in range(0, len(array), 10):
    group = array[i:i+10]
    if len(set(group)) == 1:
        print(f"数组中的元素在第 {i+1} 到第 {i+10} 个位置上相等：{group}")
    else:
        print(f"数组中的元素在第 {i+1} 到第 {i+10} 个位置上不全相等：{group}")


数组中的元素在第 1 到第 10 个位置上相等：[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
数组中的元素在第 11 到第 20 个位置上不全相等：[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
数组中的元素在第 21 到第 30 个位置上不全相等：[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [7]:
import numpy as np

# 定义一个矩阵
matrix = np.array([[1, 2, 3, 4, 5, 6],
                   [4, 5, 6, 4, 5, 6],
                   [7, 8, 9, 4, 5, 6]])

# 输出原始矩阵
print("原始矩阵：")
print(matrix)

# 使用转置操作进行行列转置
transposed_matrix = np.transpose(matrix)

# 输出转置后的矩阵
print("\n转置后的矩阵：")
print(transposed_matrix)


原始矩阵：
[[1 2 3 4 5 6]
 [4 5 6 4 5 6]
 [7 8 9 4 5 6]]

转置后的矩阵：
[[1 4 7]
 [2 5 8]
 [3 6 9]
 [4 4 4]
 [5 5 5]
 [6 6 6]]


In [ ]:
import random

# 生成一个1位随机数
random_number = random.choice(range(0, 5))

# 打印生成的随机数
print(random_number)

In [5]:
my_array = ['a', 'b', 'c']

# 使用 for 循环遍历数组
for element in my_array:
    print(element)


a
b
c


In [1]:
from tqdm import tqdm
import time

# Define the number of iterations for the loop
total_iterations = 100

# Initialize tqdm with the total number of iterations
with tqdm(total=total_iterations, desc="Processing") as pbar:
    for i in range(total_iterations):
        # Simulate some processing time
        time.sleep(0.1)
        # Update the progress bar
        pbar.update(1)

print("Processing complete!")


Processing: 100%|██████████| 100/100 [00:10<00:00,  9.47it/s]

Processing complete!


In [3]:
for i in range(0, 9):
    print(i)

0
1
2
3
4
5
6
7
8
