In [ ]:
for i in range(3):
    arr_{i} = 

In [89]:


# 定义多个二维数组
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15], [16, 17, 18]])

# 使用 numpy.stack() 函数将多个二维数组拼接成一个三维数组
three_dimensional_array = np.stack((array1, array2, array3))

# 打印三维数组
print(three_dimensional_array)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [88]:
import numpy as np

# 定义一个空的三维数组
three_dimensional_array = np.empty((0, 0, 3), dtype=int)

# 定义要添加的向量
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# 将向量添加到三维数组的第一维
three_dimensional_array = np.append(three_dimensional_array, [vector1[np.newaxis,:]], axis=0)
three_dimensional_array = np.append(three_dimensional_array, [vector2[np.newaxis,:]], axis=0)

# 打印三维数组
print(three_dimensional_array)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [85]:
import numpy as np

# 定义一个空的三维数组
three_dimensional_array = np.empty((9, 1, 3), dtype=int)

# 添加一个二维数组
two_dimensional_array1 = np.array([1, 2, 3])
three_dimensional_array = np.append(three_dimensional_array[0], [two_dimensional_array1], axis=1)

# 添加另一个二维数组
two_dimensional_array2 = np.array([7, 8, 9])
three_dimensional_array = np.append(three_dimensional_array[1], [two_dimensional_array2], axis=1)

# 打印三维数组
print(three_dimensional_array.shape)

print(three_dimensional_array)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [73]:
import numpy as np

data = [[] for _ in range(9)]

for i in range(9):
    print(i)

0
1
2
3
4
5
6
7
8


In [68]:
import numpy as np

data = [[] for _ in range(9)]
arr1 = np.array([-0.015,    0.94871, -0.06443, -0.30929, -0.16,     1.11557, -0.25971])
data[0].append(arr1)
data[0].append(arr1)
data[0].append(arr1)

print(data[0])

[[array([-0.015  ,  0.94871, -0.06443, -0.30929, -0.16   ,  1.11557,
       -0.25971]), array([-0.015  ,  0.94871, -0.06443, -0.30929, -0.16   ,  1.11557,
       -0.25971]), array([-0.015  ,  0.94871, -0.06443, -0.30929, -0.16   ,  1.11557,
       -0.25971])], [], [], [], [], [], [], [], []]


In [72]:
data[0][1:3]

[array([-0.015  ,  0.94871, -0.06443, -0.30929, -0.16   ,  1.11557,
        -0.25971]),
 array([-0.015  ,  0.94871, -0.06443, -0.30929, -0.16   ,  1.11557,
        -0.25971])]

In [62]:
import numpy as np

arr = np.arange(12).reshape((3, 4))

print(np.hsplit(arr, 4))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [59]:
import numpy as np

arr = np.arange(12).reshape((3, 4))

print(arr)

print(np.split(arr, 3, axis=0))
a, b, c = np.split(arr, 3, axis=0)
print(a, b, c)

print(np.split(arr, 3, axis=1))
d, e, f = np.split(arr, 3, axis=1)
print(d, e, f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[[0 1 2 3]] [[4 5 6 7]] [[ 8  9 10 11]]


ValueError: array split does not result in an equal division

In [54]:

arr1 = np.array([1, 1, 1])

print(arr1)
print(type(arr1))
arr1

[1 1 1]
<class 'numpy.ndarray'>


array([1, 1, 1])

In [50]:
import numpy as np
arr = np.arange(1, 13).reshape((3, 4))
print(arr)

print('type(arr.flatten)', type(arr.flatten))
print('type(arr.flat)', type(arr.flat))

for i in arr.flat:
    print(i)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
type(arr.flatten) <class 'builtin_function_or_method'>
type(arr.flat) <class 'numpy.flatiter'>
1
2
3
4
5
6
7
8
9
10
11
12


In [39]:
import numpy as np

# 定义一个空的三维数组
three_dimensional_array = [[[]]]

# 添加一个二维数组
two_dimensional_array1 = np.array([1, 2, 3])
three_dimensional_array = np.append(three_dimensional_array[0], [two_dimensional_array1], axis=1)
three_dimensional_array = np.append(three_dimensional_array[0], [two_dimensional_array1], axis=1)
three_dimensional_array = np.append(three_dimensional_array[0], [two_dimensional_array1], axis=1)


# 打印三维数组
print(three_dimensional_array[0])


AxisError: axis 1 is out of bounds for array of dimension 1

In [21]:
import numpy as np
# 4. Stack Arrays
data = np.array()
array1 = np.array([1, 2])
array2 = np.array([5, 6])
array3 = np.array([7, 8])
data = np.vstack((data, array2))
data = np.vstack((data, array3))

print("Stacked Vertically:\n", stacked_vertically)

TypeError: array() missing required argument 'object' (pos 0)

In [7]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# 1. Modify Existing Elements
array[0] = 10
print("Modified Array:", array)

# 2. Append New Elements
array = np.append(array, [6, 7])
print("Appended Array:", array)

# 3. Insert New Elements
array = np.insert(array, 2, [8, 9])
print("Inserted Array:", array)

# 4. Stack Arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
stacked_vertically = np.vstack((array1, array2))
stacked_horizontally = np.hstack((array1, array2))

print("Stacked Vertically:\n", stacked_vertically)
print("Stacked Horizontally:\n", stacked_horizontally)


Modified Array: [10  2  3  4  5]
Appended Array: [10  2  3  4  5  6  7]
Inserted Array: [10  2  8  9  3  4  5  6  7]
Stacked Vertically:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Stacked Horizontally:
 [[1 2 5 6]
 [3 4 7 8]]


In [6]:
import numpy as np

# Create a NumPy ndarray
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(ndarray)
# Convert the ndarray to a Python list
python_list = ndarray.tolist()

# Print the Python list
print(python_list)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [4]:
# 定义空的二维数组
empty_two_dimensional_array = []

# 添加第一行
row1 = [1, 2, 3]
empty_two_dimensional_array.append(row1)

# 添加第二行
row2 = [4, 5, 6]
empty_two_dimensional_array.append(row2)

# 添加第三行
row3 = [7, 8, 9]
empty_two_dimensional_array.append(row3)

# 打印二维数组
print(empty_two_dimensional_array)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [3]:
# 定义一个三维数组
three_dimensional_array = [
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
]

# 使用多重嵌套循环遍历三维数组
for i in three_dimensional_array:
    print(i)
    #print(f"Element at index ({i}) is {three_dimensional_array[i]}")

[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]
[[13, 14, 15], [16, 17, 18]]


In [1]:
# 定义一个三维数组
three_dimensional_array = [
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
]

# 使用多重嵌套循环遍历三维数组
for i in range(len(three_dimensional_array)):
    for j in range(len(three_dimensional_array[i])):
        for k in range(len(three_dimensional_array[i][j])):
            print(f"Element at index ({i}, {j}, {k}) is {three_dimensional_array[i][j][k]}")


Element at index (0, 0, 0) is 1
Element at index (0, 0, 1) is 2
Element at index (0, 0, 2) is 3
Element at index (0, 1, 0) is 4
Element at index (0, 1, 1) is 5
Element at index (0, 1, 2) is 6
Element at index (1, 0, 0) is 7
Element at index (1, 0, 1) is 8
Element at index (1, 0, 2) is 9
Element at index (1, 1, 0) is 10
Element at index (1, 1, 1) is 11
Element at index (1, 1, 2) is 12
Element at index (2, 0, 0) is 13
Element at index (2, 0, 1) is 14
Element at index (2, 0, 2) is 15
Element at index (2, 1, 0) is 16
Element at index (2, 1, 1) is 17
Element at index (2, 1, 2) is 18
