In [1]:
import pandas as pd
import tqdm.auto as tqdm

complete_to_two_digits = lambda x: str(x).zfill(2) if x < 10 else str(x)

def read_csv_file(user_id, video_id):
    filepath = f'../sensory/raw/{video_id}_user{user_id}_raw.csv'
    #print(filepath)
    df = pd.read_csv(filepath)
    
    return df

csv_data = []
video_dict = {'coaster': 0, 'coaster2': 1, 'diving': 2, 'drive': 3, 'game': 4, 'landscape': 5, 'pacman': 6, 'panel': 7, 'ride': 8, 'sport': 9}
# video_ids = ['coaster', 'coaster2', 'diving', 'drive', 'game', 'landscape', 'pacman', 'panel', 'ride', 'sport']
for user_id in range(1, 51):
    user_data = []
    for video_id in video_dict.keys():

        df = read_csv_file(complete_to_two_digits(user_id), video_id)
 
        df['user_id'] = user_id # 添加标签（用户ID）
        df['video_id'] = video_dict[video_id] # 添加video_id字段
        df['timestamp'] = pd.to_datetime(df['timestamp'], unit='s')
        df['timestamp_floor'] = pd.to_datetime(df['timestamp'], unit='s').dt.floor('100ms')
        user_data.append(df)

    user_data_combined = pd.concat(user_data, ignore_index=True)
    csv_data.append(user_data_combined)

csv_data = pd.concat(csv_data, ignore_index=True)


In [3]:
csv_data

timestamp   rawTX   rawTY  rawTZ  rawYaw  \
0        2017-03-17 08:09:50.316999936  10.073  -0.109 -0.587 -16.907   
1        2017-03-17 08:09:50.324999936  10.071  -0.108 -0.587 -16.907   
2        2017-03-17 08:09:50.328999936  10.070  -0.109 -0.587 -16.907   
3        2017-03-17 08:09:50.332999936  10.069  -0.108 -0.588 -16.907   
4        2017-03-17 08:09:50.336999936  10.068  -0.109 -0.588 -16.908   
...                                ...     ...     ...    ...     ...   
13188502 2017-02-15 07:45:58.303000064  47.180  23.764 -6.570   1.757   
13188503 2017-02-15 07:45:58.306999808  47.179  23.759 -6.561   1.775   
13188504 2017-02-15 07:45:58.311000064  47.177  23.747 -6.542   1.811   
13188505 2017-02-15 07:45:58.313999872  47.175  23.736 -6.523   1.848   
13188506 2017-02-15 07:45:58.320000000  47.169  23.720 -6.495   1.910   

          rawPitch  rawRoll  user_id  video_id         timestamp_floor  
0           -1.869   -2.928        1         0 2017-03-17 08:09:50.300  
1           -1.870   -2.930        1         0 2017-03-17 08:09:50.300  
2           -1.870   -2.931        1         0 2017-03-17 08:09:50.300  
3           -1.870   -2.933        1         0 2017-03-17 08:09:50.300  
4           -1.869   -2.934        1         0 2017-03-17 08:09:50.300  
...            ...      ...      ...       ...                     ...  
13188502   -12.715   -1.601       50         9 2017-02-15 07:45:58.300  
13188503   -12.739   -1.605       50         9 2017-02-15 07:45:58.300  
13188504   -12.785   -1.615       50         9 2017-02-15 07:45:58.300  
13188505   -12.828   -1.627       50         9 2017-02-15 07:45:58.300  
13188506   -12.899   -1.660       50         9 2017-02-15 07:45:58.300  

[13188507 rows x 10 columns]

In [2]:
from datetime import timedelta
import numpy as np
import random
from tqdm.auto import tqdm

def process_data(csv_data):

    data_0, data_1, data_2, data_3, data_4, data_5, data_6, data_7, data_8, data_9 = [], [], [], [], [], [], [], [], [], []
    labels_0, labels_1, labels_2, labels_3, labels_4, labels_5, labels_6, labels_7, labels_8, labels_9 = [], [], [], [], [], [], [], [], [], []

    for user_id, user_data in tqdm(csv_data.groupby('user_id')):
        for video_id, video_data in user_data.groupby('video_id'):
            for _, floor_data in video_data.groupby(video_data['timestamp_floor']):
                floor_data = floor_data[['rawTX', 'rawTY', 'rawTZ', 'rawYaw', 'rawPitch', 'rawRoll']]
                if video_id == 0:
                    data_0.append(round(floor_data.mean(), 5).values)
                    labels_0.append(user_id)
                elif video_id == 1:
                    data_1.append(round(floor_data.mean(), 5).values)
                    labels_1.append(user_id)
                elif video_id == 2:
                    data_2.append(round(floor_data.mean(), 5).values)
                    labels_2.append(user_id)
                elif video_id == 3:
                    data_3.append(round(floor_data.mean(), 5).values)
                    labels_3.append(user_id)
                elif video_id == 4:
                    data_4.append(round(floor_data.mean(), 5).values)
                    labels_4.append(user_id)
                elif video_id == 5:
                    data_5.append(round(floor_data.mean(), 5).values)
                    labels_5.append(user_id)
                elif video_id == 6:
                    data_6.append(round(floor_data.mean(), 5).values)
                    labels_6.append(user_id)
                elif video_id == 7:
                    data_7.append(round(floor_data.mean(), 5).values)
                    labels_7.append(user_id)
                elif video_id == 8:
                    data_8.append(round(floor_data.mean(), 5).values)
                    labels_8.append(user_id)
                elif video_id == 9:
                    data_9.append(round(floor_data.mean(), 5).values)
                    labels_9.append(user_id)

    return np.array(data_0), np.array(labels_0), np.array(data_1), np.array(labels_1), \
            np.array(data_2), np.array(labels_2), np.array(data_3), np.array(labels_3), \
            np.array(data_4), np.array(labels_4), np.array(data_5), np.array(labels_5), \
            np.array(data_6), np.array(labels_6), np.array(data_7), np.array(labels_7), \
            np.array(data_8), np.array(labels_8), np.array(data_9), np.array(labels_9)

In [3]:
data_0, labels_0, data_1, labels_1, data_2, labels_2, \
    data_3, labels_3, data_4, labels_4, data_5, labels_5, \
        data_6, labels_6, data_7, labels_7, data_8, labels_8, data_9, labels_9 = process_data(csv_data)

  0%|          | 0/50 [00:00<?, ?it/s]

In [4]:
print('data_0.shape: {}'.format(data_0.shape))
print('labels_0.shape: {}'.format(labels_0.shape))
print('data_1.shape: {}'.format(data_1.shape))
print('labels_1.shape: {}'.format(labels_1.shape))
print('data_2.shape: {}'.format(data_2.shape))
print('labels_2.shape: {}'.format(labels_2.shape))
print('data_3.shape: {}'.format(data_3.shape))
print('labels_3.shape: {}'.format(labels_3.shape))
print('data_4.shape: {}'.format(data_4.shape))
print('labels_4.shape: {}'.format(labels_4.shape))
print('data_5.shape: {}'.format(data_5.shape))
print('labels_5.shape: {}'.format(labels_5.shape))
print('data_6.shape: {}'.format(data_6.shape))
print('labels_6.shape: {}'.format(labels_6.shape))
print('data_7.shape: {}'.format(data_7.shape))
print('labels_7.shape: {}'.format(labels_7.shape))
print('data_8.shape: {}'.format(data_8.shape))
print('labels_8.shape: {}'.format(labels_8.shape))
print('data_9.shape: {}'.format(data_8.shape))
print('labels_9.shape: {}'.format(labels_8.shape))


data_0.shape: (53113, 6)
labels_0.shape: (53113,)
data_1.shape: (54669, 6)
labels_1.shape: (54669,)
data_2.shape: (52851, 6)
labels_2.shape: (52851,)
data_3.shape: (52711, 6)
labels_3.shape: (52711,)
data_4.shape: (52355, 6)
labels_4.shape: (52355,)
data_5.shape: (53246, 6)
labels_5.shape: (53246,)
data_6.shape: (52395, 6)
labels_6.shape: (52395,)
data_7.shape: (52414, 6)
labels_7.shape: (52414,)
data_8.shape: (52850, 6)
labels_8.shape: (52850,)
data_9.shape: (52850, 6)
labels_9.shape: (52850,)


In [5]:
print(data_8)
print(data_9)

[[ 12.779    -4.20578  -1.90044 -28.02333  -9.70611  -4.26833]
 [ 12.78052  -4.23208  -1.93232 -28.0242   -9.8022   -4.26324]
 [ 12.77932  -4.25248  -1.98876 -27.92876 -10.0106   -4.2654 ]
 ...
 [ 53.52492  27.51824  -1.11256  13.49136  10.87908 -11.53852]
 [ 53.0534   27.3916   -1.04244  14.1996   10.62696 -12.34256]
 [ 52.7675   27.35075  -0.996    14.5855   10.39925 -12.859  ]]
[[ 10.762    -4.0245   -0.926   -18.239    -9.4045   -2.0035 ]
 [ 10.76304  -4.01444  -0.93384 -18.25472  -9.34136  -2.00524]
 [ 10.7638   -3.99848  -0.95236 -18.23376  -9.29352  -2.01196]
 ...
 [ 47.11244  24.21812  -7.39356   0.75056 -10.59816  -1.8866 ]
 [ 47.17996  23.91444  -6.84324   1.3474  -12.04668  -1.63276]
 [ 47.176    23.7452   -6.5382    1.8202  -12.7932   -1.6216 ]]


In [6]:
def append_to_file(input_file, output_file, additional_content):
    with open(input_file, 'r') as f:
        original_content = f.read()

    new_content = original_content + '\n' + additional_content

    with open(output_file, 'w') as f:
        f.write(new_content)


In [7]:
def initTimeNetData(data, label, step):
    append_string = ""
    for i in range(0, len(label), step):
        group = label[i:i+step]
        if len(set(group)) == 1:
            temp_transposed_matrix = np.transpose(data[i:i+step])
            append_string += ":".join([",".join(map(str, row)) for row in temp_transposed_matrix])
            append_string += ":" + str(group[0]) + "\n"

    return append_string

In [8]:
for i in range(10):
    train_data = []
    train_labels = []
    test_data = []
    test_labels = []
    if i == 0:
        print(f'i: {i}, initiate data start.')
        train_data = np.vstack((data_1, data_2, data_3, data_4, data_5, data_6, data_7, data_8, data_9))
        train_labels = np.hstack((labels_1, labels_2, labels_3, labels_4, labels_5, labels_6, labels_7, labels_8, labels_9))
        test_data = data_0
        test_labels = labels_0
        print(f'i: {i}, initiate data finished.')
    elif i == 1:
        print(f'i: {i}, initiate data start.')
        train_data = np.vstack((data_0, data_2, data_3, data_4, data_5, data_6, data_7, data_8, data_9))
        train_labels = np.hstack((labels_0, labels_2, labels_3, labels_4, labels_5, labels_6, labels_7, labels_8, labels_9))
        test_data = data_1
        test_labels = labels_1
        print(f'i: {i}, initiate data finished.')
    elif i == 2:
        print(f'i: {i}, initiate data start.')
        train_data = np.vstack((data_0, data_1, data_3, data_4, data_5, data_6, data_7, data_8, data_9))
        train_labels = np.hstack((labels_0, labels_1, labels_3, labels_4, labels_5, labels_6, labels_7, labels_8, labels_9))
        test_data = data_2
        test_labels = labels_2
        print(f'i: {i}, initiate data finished.')
    elif i == 3:
        print(f'i: {i}, initiate data start.')
        train_data = np.vstack((data_0, data_1, data_2, data_4, data_5, data_6, data_7, data_8))
        train_labels = np.hstack((labels_0, labels_1, labels_2, labels_4, labels_5, labels_6, labels_7, labels_8, labels_9))
        test_data = data_3
        test_labels = labels_3
        print(f'i: {i}, initiate data finished.')
    elif i == 4:
        print(f'i: {i}, initiate data start.')
        train_data = np.vstack((data_0, data_1, data_2, data_3, data_5, data_6, data_7, data_8, data_9))
        train_labels = np.hstack((labels_0, labels_1, labels_2, labels_3, labels_5, labels_6, labels_7, labels_8, labels_9))
        test_data = data_4
        test_labels = labels_4
    elif i == 5:
        print(f'i: {i}, initiate data start.')
        train_data = np.vstack((data_0, data_1, data_2, data_3, data_4, data_6, data_7, data_8, data_9))
        train_labels = np.hstack((labels_0, labels_1, labels_2, labels_3, labels_4, labels_6, labels_7, labels_8, labels_9))
        test_data = data_5
        test_labels = labels_5
        print(f'i: {i}, initiate data finished.')
    elif i == 6:
        print(f'i: {i}, initiate data start.')
        train_data = np.vstack((data_0, data_1, data_2, data_3, data_4, data_5, data_7, data_8, data_9))
        train_labels = np.hstack((labels_0, labels_1, labels_2, labels_3, labels_4, labels_5, labels_7, labels_8, labels_9))
        test_data = data_6
        test_labels = labels_6
        print(f'i: {i}, initiate data finished.')
    elif i == 7:
        print(f'i: {i}, initiate data start.')
        train_data = np.vstack((data_0, data_1, data_2, data_3, data_4, data_5, data_6, data_8, data_9))
        train_labels = np.hstack((labels_0, labels_1, labels_2, labels_3, labels_4, labels_5, labels_6, labels_8, labels_9))
        test_data = data_7
        test_labels = labels_7
        print(f'i: {i}, initiate data finished.')
    elif i == 8:
        print(f'i: {i}, initiate data start.')
        train_data = np.vstack((data_0, data_1, data_2, data_3, data_4, data_5, data_6, data_7, data_9))
        train_labels = np.hstack((labels_0, labels_1, labels_2, labels_3, labels_4, labels_5, labels_6, labels_7, labels_9))
        test_data = data_8
        test_labels = labels_8
        print(f'i: {i}, initiate data finished.')
    elif i == 9:
        print(f'i: {i}, initiate data start.')
        train_data = np.vstack((data_0, data_1, data_2, data_3, data_4, data_5, data_6, data_7, data_8))
        train_labels = np.hstack((labels_0, labels_1, labels_2, labels_3, labels_4, labels_5, labels_6, labels_7, labels_8))
        test_data = data_9
        test_labels = labels_9
        print(f'i: {i}, initiate data finished.')

    print('train_data.shape: {}'.format(train_data.shape))
    print('train_labels.shape: {}'.format(train_labels.shape))
    print('test_data.shape: {}'.format(test_data.shape))
    print('test_labels.shape: {}'.format(test_labels.shape))

    print(f'generate UserIdentify{i}_TRAIN.ts begin')
    append_train_string = initTimeNetData(train_data, train_labels, 16)
    append_to_file('template.ts', f'UserIdentify{i}_TRAIN.ts', append_train_string)
    print(f'generate UserIdentify{i}_TRAIN.ts finished.')
    print(f'generate UserIdentify{i}_TEST.ts begin')
    append_test_string = initTimeNetData(test_data, test_labels, 16)
    append_to_file('template.ts', f'UserIdentify{i}_TEST.ts', append_test_string)
    print(f'generate UserIdentify{i}_TEST finished.ts')

i: 0, initiate data start.
i: 0, initiate data finished.
train_data.shape: (475271, 6)
train_labels.shape: (475271,)
test_data.shape: (53113, 6)
test_labels.shape: (53113,)
generate UserIdentify0_TRAIN.ts begin
generate UserIdentify0_TRAIN.ts finished.
generate UserIdentify0_TEST.ts begin
generate UserIdentify0_TEST finished.ts
i: 1, initiate data start.
i: 1, initiate data finished.
train_data.shape: (473715, 6)
train_labels.shape: (473715,)
test_data.shape: (54669, 6)
test_labels.shape: (54669,)
generate UserIdentify1_TRAIN.ts begin
generate UserIdentify1_TRAIN.ts finished.
generate UserIdentify1_TEST.ts begin
generate UserIdentify1_TEST finished.ts
i: 2, initiate data start.
i: 2, initiate data finished.
train_data.shape: (475533, 6)
train_labels.shape: (475533,)
test_data.shape: (52851, 6)
test_labels.shape: (52851,)
generate UserIdentify2_TRAIN.ts begin
generate UserIdentify2_TRAIN.ts finished.
generate UserIdentify2_TEST.ts begin
generate UserIdentify2_TEST finished.ts
i: 3, init